name: release-workflow
on:
  release:
    types:
      - created
jobs:
  package_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Show Project ...
        run: ls -al
      - name: Compile
        run: make build
      - name: Packaging...
        run: tar -zcvf fsync.tgz ./bin/*
      - name: Uploading assets...
        if: ${{ !env.ACT }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fsync.tgz
          asset_name: fsync.tgz
          asset_content_type: application/gzip